service:
  name: 'prod service for service b'
student:
  data:
    - name: 'Sanghui Park'
      studentId: '201935044'

logging:
  level:
    # Due to requirement of the project, we are not going to set it as WARN
    root: WARN
